### PR TITLE
Credo

### PR DESCRIPTION
**Pull request by Kloenk**
Credo is a tool to analyse Elixir sources, this also should annotate PRs with possible fixes.

### CODE REVIEW

**Comment by drupol** [comment]
I guess this needs a rebase?

Also, it seems that there is an error:

image

But the ci returns green, is it the intended behavior?

**Comment by Kloenk** [comment]
It's GitHub, which sadly does not let me test the ci, not even on my own repo. So not totally sure

**Comment by alxlion** [comment]
It's ready to be merged, just waiting for your changes https://github.com/ClaperCo/Claper/pull/18/files/f56a548612239ae89c80818e4e41c819c3a7bf20#diff-f536705d9b40299999eea4f9558c34a35b345f3ccc3c8f0315aea8413e095fe6

**Comment by Kloenk** [comment]
Thanks, don't think i will find time today, but plan to do it tomorrow

**Pull request closed without merging**
